
abstract: Create and manipulate PAR distributions
author: Audrey Tang (autrijus@autrijus.org)
distribution_type: module
generated_by: Module::Install version 0.56
license: perl
name: PAR-Dist
no_index: 
  directory: 
    - inc
    - t
version: 0.08
