name: PAR-Dist
version: 0.07
abstract: Create and manipulate PAR distributions
author: Autrijus Tang (autrijus@autrijus.org)
license: perl
distribution_type: module
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.31
