abstract: Create and manipulate PAR distributions
author: Audrey Tang (autrijus@autrijus.org)
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: PAR-Dist
no_index: 
  directory: 
    - inc
    - t
requires: 
  Cwd: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
version: 0.18
